apiVersion: v1
kind: Secret
metadata:
  name: redis-auth-nova
  namespace: redis-system
type: Opaque
data:
  password: aGVsbG8=
---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis-nova
  namespace: redis-system
spec:
  auth:
    secretPath: redis-auth-nova
  sharding: 1
  redis:
    replicas: 2
    maxmemory: 1gb
    image: 10.12.28.4:80/run/redis-alpine:1.0.0
    imagePullSecrets:
    - name: harborkey
    imagePullPolicy: IfNotPresent
    nodeSelector:
      aggregate: default
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
    exporter: 
      enabled: true
      image: oliver006/redis_exporter:v1.3.5-alpine
      args:
        - --web.telemetry-path
        - /metrics
      env:
        - name: REDIS_EXPORTER_LOG_FORMAT
          value: txt
  sentinel:
    replicas: 3
    image: 10.12.28.4:80/run/redis-alpine:1.0.0
    imagePullSecrets:
    - name: harborkey
    imagePullPolicy: IfNotPresent
    nodeSelector:
      aggregate: default
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
    exporter:
      enabled: true
      image: leominov/redis_sentinel_exporter:1.3.0
  predixy:
    replicas: 2
    image: 10.12.28.4:80/run/predixy:1.2.0
    imagePullSecrets:
    - name: harborkey
    imagePullPolicy: IfNotPresent
    nodeSelector:
      aggregate: default
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 500m
        memory: 1024Mi
    exporter:
      enabled: true
      image: 10.12.28.4:80/service/predixy_exporter:1.0.1
    podAnnotations:
      ovn.kubernetes.io/ip_pool: 10.16.4.10,10.16.4.11
      ovn.kubernetes.io/logical_switch: ovn-default

