apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
  redis:
    replicas: 3
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
