---
apiVersion: v1
kind: Namespace
metadata:
  name: sc
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: sc
type: Opaque
stringData:
  password: pass
---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: sidecars
  namespace: sc
spec:
  auth:
    secretPath: redis-auth
  sentinel:
    initContainers:
    - name: echo
      image: busybox
      command:
      - "/bin/sh"
      - "-c"
      - "echo 'init container sentinel'"
    replicas: 3
    extraContainers:
    - name: busybox
      image: busybox
      command:
      - "/bin/sh"
      - "-c"
      - "sleep infinity"
  redis:
    replicas: 3
    initContainers:
    - name: echo
      image: busybox
      command:
      - "/bin/sh"
      - "-c"
      - "echo 'init container redis'"
    extraContainers:
    - name: busybox
      image: busybox
      command:
      - "/bin/sh"
      - "-c"
      - "sleep infinity"
