---
apiVersion: v1
kind: Namespace
metadata:
  name: tsc
---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis-tsc
  namespace: tsc
spec:
  redis:
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: redis
      maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: redis
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
  sentinel:
    replicas: 3
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: sentinel
      maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: sentinel
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
